### ISSUE TITLE
32-bit build failing due to sign mismatch warning and treat warnings as errors

### ISSUE THREAD

**Issue by vinsworldcom** [daddel80/notepadpp-multireplace#13]
When building the 32-bit version, I'm getting several warnings about sign mismatch in "src\MultiReplace.cpp":

```
notepadpp-multireplace\src\MultiReplace.cpp(448,42):  warning C4018: '>=': signed/unsigned mismatch [notepadpp-multireplace\vs.proj\NppMultiReplace.vcxproj]
notepadpp-multireplace\src\MultiReplace.cpp(467,42):  warning C4018: '>=': signed/unsigned mismatch [notepadpp-multireplace\vs.proj\NppMultiReplace.vcxproj]
notepadpp-multireplace\src\MultiReplace.cpp(502,129): warning C4389: '==': signed/unsigned mismatch [notepadpp-multireplace\vs.proj\NppMultiReplace.vcxproj]
notepadpp-multireplace\src\MultiReplace.cpp(1077,14): warning C4018: '<':  signed/unsigned mismatch [notepadpp-multireplace\vs.proj\NppMultiReplace.vcxproj]
notepadpp-multireplace\src\MultiReplace.cpp(1131,30): warning C4018: '>=': signed/unsigned mismatch [notepadpp-multireplace\vs.proj\NppMultiReplace.vcxproj]
notepadpp-multireplace\src\MultiReplace.cpp(1290,28): warning C4018: '<=': signed/unsigned mismatch [notepadpp-multireplace\vs.proj\NppMultiReplace.vcxproj]
notepadpp-multireplace\src\MultiReplace.cpp(1581,40): warning C4018: '<':  signed/unsigned mismatch [notepadpp-multireplace\vs.proj\NppMultiReplace.vcxproj]
```

The build fails since in "vs.proj\NppMultiReplace.vcxproj", the `<TreatWarningAsError>true</TreatWarningAsError>` is set in all the `ItemDefinitionGroup`'s.

You could just set that to false for the 32-bit build configurations.  Better would be to examine how / why the comparisons are between `int` and `size_t` (in most cases) and see if that could be fixed or just cast the `size_t` to `int` minding:

https://stackoverflow.com/questions/3642010/can-i-compare-int-with-size-t-directly-in-c

Cheers.

**Comment by daddel80** [comment]
Thanks for pointing this out. I have fixed it in the latest upload from yesterday. Yes, there were different behaviors between 64-bit and 32-bit compilation before.
