### ISSUE TITLE
"export to Bash"

### ISSUE THREAD

**Issue by RWolfer** [daddel80/notepadpp-multireplace#28]
Tested under Windows MingGW64 (comes with Git)

Error: sed: -e expression #1, char 13: unknown option to `s'

Solution (tested and working!) https://unix.stackexchange.com/questions/91630/sed-unknown-option-to-s
I have replaced the delimiter in template to pipe: example:     if [[ "$matchCase" -eq 1 ]]; then
        template='s|'${findString}'|'${replaceString}'|g'
    else
        template='s|'${findString}'|'${replaceString}'|gi'

**Comment by daddel80** [comment]
version 1.0.3.4
