### ISSUE TITLE
The newer versions can't not run on NPP v8.5.7 x64

### ISSUE THREAD

**Issue by mixboser** [daddel80/notepadpp-multireplace#32]
I can't run 1.1.0-RC1, 1.1.0.5 or 1.1.1.6 on NPP v8.5.7 x64.  But 1.0.3.4 is still working.  Thanks.

**Comment by mixboser** [comment]
By the way, the Plugins Admin still shows 1.0.3.4.  I was able to manually download and use 1.1.0-RC1 few weeks ago before the latest NPP update.

**Comment by daddel80** [comment]
The 1.1 versions are still not published by NPP, if you mean that. It depends on NPP when they decide to update the version in the Plugin list. But you can download it here and copy it into your Plugin folder.
