### ISSUE TITLE
Ability to translate the plugin

### ISSUE THREAD

**Issue by VerNOX21** [daddel80/notepadpp-multireplace#34]
Good afternoonю If it's possible and if it's not difficult, could you add the ability for everyone (me in particular) to translate your plugin into their native language? For example, how this is implemented in NotePad++: there is an XML file that can be edited and get the result that you need. I use your plugin to modify games, correct official localizations, and it’s just nice when all the space around you is in your native language :)

Thank you!

**Comment by daddel80** [comment]
Hi VerNOX21, thanks for your feedback and for sharing how you use the plugin. It's always interesting to hear. I've been considering support for multiple languages but was still unsure about it. Your message has given me the push to implement this. I'll aim to include it in one of the upcoming releases. Thanks for the idea, and I wish you a peaceful New Year.

Thomas

**Comment by VerNOX21** [comment]
Thank you Thomas. I, too, from the bottom of my heart wish you inner harmony and peace in your soul this year.
Your plugin became the basis of my hobby of translating games and programs. In fact, it's practically perfect. For example, it immediately highlights the line “Find what”, which is very convenient and something that is not in the original NotePad++ search. You made a cool tool. But I will allow myself one more question-request. Is it possible for plugins to remember the window size when NotePad++ is closed? I work with a large number of lines, approximately in this format (see screenshot), and each time I stretch it to the desired height.

![1](https://github.com/daddel80/notepadpp-multireplace/assets/123237774/66244224-72c0-457b-aafb-39ae6e1d3165)

**Comment by daddel80** [comment]
Hi VerNox21,
Thanks for the screenshots which are showing me the value the tool is giving to you.
you wrote: "Is it possible for plugins to remember the window size when NotePad++ is closed?"
Thats indeed a good point i will enhance in one of the next versions.

The prelease for the multi-language support is almost ready and can probably be tested next week.  As my Russian is a bit rusty maybe you can help polishing it in the languages.ini file. If you want to support i can handover a prerelease to you if it is ready. Just contact me via daddel80[at]outlook.com if you are interested. 

Thomas

**Comment by VerNOX21** [comment]
Here’s another option, from my personal experience, that could be useful. When using the Mark Matches (or even Replace All) option, mark which items from the list were used and which were not. This would make finding broken or irrelevant rows very easy and simple.

**Comment by daddel80** [comment]
Hi VerNox21, you are full of good ideas. :-) I agree, a special column in the list showing the number of hits can be helpfull. I will put it on the list for a further release. Thanks you

PS: As i told you the MultiLangauge option will soon be ready. I will start filling it in Russian but it would be helpfull if you can correct it, I will tell you here How to do that in case you prefer sharing here.

**Comment by VerNOX21** [comment]
You can even mark the cells in this column with a color, green if x>0 and, for example, gray if x=0.
I wrote to you by email, but perhaps the letter did not arrive... In any case, I am happy to participate in the translation, polish it and bring it to perfection =)
Just in case, my email: vernoxpower[at]gmail com

**Comment by daddel80** [comment]
I agree that colorizing would be much 'lighter' for the complexity of the Plugin. But unfortunatly the possibilities for such options are limited by the Notepad++ Plugin Framework. But i will investigate what is still possible.

Thanks for your input as it helps to improve usability. User experiences are very valuable!!

I sent you an email. I didn't received your first one.

**Comment by daddel80** [comment]
MultiLanguage will be supported in version 2.4.0.11.
