### ISSUE TITLE
Capture variables does not reset

### ISSUE THREAD

**Issue by andry81** [daddel80/notepadpp-multireplace#48]
Example:

```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
D:\test test\test1.txt
#> c:\test2\test2.txt.lnk
D:\test test\|test2.txt
```

Find what:
```regex
^([^\r\n\|]+)(?:\|([^\r\n\|]+)(?:\|([^\r\n\|]+)(?:\|([^\r\n\|]+))?)?)?
```

Replace with:
```lua
init({DESTDIR="",REPLACETO=""}); 

if CAP1 ~= nil and string.sub(CAP1,1,3) == "#> " then
  if CAP2 ~= nil and string.len(CAP2) > 0 then
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^(.+)")
  else
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^(.+\\\\)")
  end;
elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= "#" and DESTDIR ~= nil and string.len(DESTDIR) > 0 and CAP2 ~= nil then
  REPLACETO=DESTDIR.."|"..CAP2 
else
  REPLACETO=nil 
end; 

cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) > 0 and string.len(CAP2) > 0 and string.sub(CAP1,1,1) ~= "#" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO)
```

[x] Use Variables
Search Mode: Regular expression
[x] Use List

Result:
```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\|test1.txt.lnk
#> c:\test2\test2.txt.lnk
c:\test2\test2.txt.lnk|test2.txt
```

Expectation:
```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\|test1.txt.lnk
#> c:\test2\test2.txt.lnk
c:\test2\|test2.txt
```

If try to change the code to lookup the `CAP2`:

```lua
init({DESTDIR="",REPLACETO=""}); 

if CAP1 ~= nil and string.sub(CAP1,1,3) == "#> " then
  if CAP2 ~= nil and string.len(CAP2) > 0 then
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^(.+)")..";"..CAP2..";"
  else
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^(.+\\\\)")
  end;
elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= "#" and DESTDIR ~= nil and string.len(DESTDIR) > 0 and CAP2 ~= nil then
  REPLACETO=DESTDIR.."|"..CAP2 
else
  REPLACETO=nil 
end; 

cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) > 0 and string.len(CAP2) > 0 and string.sub(CAP1,1,1) ~= "#" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO)
```

Result:
```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\;test1.txt.lnk;|test1.txt.lnk
#> c:\test2\test2.txt.lnk
c:\test2\test2.txt.lnk;test1.txt.lnk;|test2.txt
```

Expectation:
```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\;test1.txt.lnk;|test1.txt.lnk
#> c:\test2\test2.txt.lnk
c:\test2\test2.txt.lnk;;|test2.txt
```
As you see `CAP2` must be `nil` as there is no expression to match (has no `|` character), but the parser leaves `CAP` variables from a previous match.

And seems I can not reset `CAP` variables. These won't work:

```lua
init({DESTDIR="",REPLACETO=""}); 

if CAP1 ~= nil and string.sub(CAP1,1,3) == "#> " then
  if CAP2 ~= nil and string.len(CAP2) > 0 then
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^(.+)")..";"..CAP2..";"
  else
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^(.+\\\\)")
  end; 
elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= "#" and DESTDIR ~= nil and string.len(DESTDIR) > 0 and CAP2 ~= nil then
  REPLACETO=DESTDIR.."|"..CAP2 
else
  REPLACETO="" 
end; 

cond(CAP1 ~= nil and CAP2 ~= nil and string.len(CAP1) > 0 and string.len(CAP2) > 0 and string.sub(CAP1,1,1) ~= "#" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO); 

if CAP1 ~= nil and string.sub(CAP1,1,1) ~= "#" then
  CAP2=nil 
end;  
```

Result:
```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\;test1.txt.lnk;|test1.txt.lnk
#> c:\test2\test2.txt.lnk
c:\test2\test2.txt.lnk;test1.txt.lnk;|test2.txt
```

**Comment by daddel80** [comment]
Hi andry81,

I see your point. I've made surewith the next build  that the CAP variables are now deleted before the next find/replace operation. This should fix the issue you were experiencing. However, your expected results still differ slightly, but the outcome is different from what you saw previously.

I've also enhanced the DEBUG feature to show the CAP variables. Just change your first line to:
```lua
init({DESTDIR="",REPLACETO="",DEBUG=true}); 
```

Please give this fix a try. [You can install this build and see how it works. ](https://github.com/daddel80/notepadpp-multireplace/actions/runs/10012132149)

 Let me know how it goes!

Thomas

**Comment by andry81** [comment]
> Please give this fix a try. [You can install this build and see how it works. ](https://github.com/daddel80/notepadpp-multireplace/actions/runs/10012132149)

I've improved the code and it still has wrong last replacement with old `DESTDIR` value:

```lua
init({DESTDIR="",DESTFILE="",REPLACETO=""}); 

if CAP1 ~= nil and string.sub(CAP1,1,3) == "#> " then
  if CAP2 ~= nil and string.len(CAP2) > 0 then
    DESTDIR=string.sub(CAP1,4,-1)
  else
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^.+(?:\\\\|/)")
  end; 
elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= "#" and DESTDIR ~= nil and string.len(DESTDIR) > 0 then
  if CAP2 ~= nil then
    REPLACETO=DESTDIR.."|"..CAP2
  else
    _, _, DESTFILE=string.find(CAP1,"([^\\\\//]+)$"); 
    REPLACETO=DESTDIR..DESTFILE
  end; 
else
  REPLACETO=nil 
end; 

cond(CAP1 ~= nil and string.len(CAP1) > 0 and string.sub(CAP1,1,1) ~= "#" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO)
```

Result:

```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\test1.txt
#> c:\test2\test2.txt.lnk
c:\test1\|test2.txt
```

Expectation:

```txt
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\test1.txt
#> c:\test2\test2.txt.lnk
c:\test2\|test2.txt
```

**Comment by daddel80** [comment]
Hi andry81,

The reason for the difference is the missing pipe sign in the 4th line, like you have in line 2. This will lead to only CAP1 being in line 4 and no CAP2; therefore, DESTDIR will not be refreshed with the content of line 4.

Even lines 3 and 5 are different regarding the pipe (which has no impact on the result), but I would guess it slipped into the wrong line.

Original Source:
```
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
D:\test test\test1.txt
#> c:\test2\test2.txt.lnk
D:\test test\|test2.txt
```

Corrected Source:
```
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
D:\test test\test1.txt
#> c:\test2\|test2.txt.lnk
D:\test test\test2.txt
```

Result (with your latest code):
```
# dest: "d:\blabla"
#> c:\test1\|test1.txt.lnk
c:\test1\test1.txt
#> c:\test2\|test2.txt.lnk
c:\test2\test2.txt
```

PS: If the pipes are set intentionally, the code has to be adapted. Just let me know, and I will assist you.

Besides, I have prepared a newer build with a more enhanced DEBUG window, including 'Next' and 'Stop' buttons. It's not ready yet, but it is much better for testing and copying the results. [You can download it here.](https://github.com/daddel80/notepadpp-multireplace/actions/runs/10028599377)

**Comment by andry81** [comment]
> The reason for the difference is the missing pipe sign in the 4th line, like you have in line 2. This will lead to only CAP1 being in line 4 and no CAP2; therefore, DESTDIR will not be refreshed with the content of line 4.

No, I've changed the code. There is no need to be the pipe sign. If the pipe does not exist, then `CAP2` is nil:

```lua
  if CAP2 ~= nil then
    REPLACETO=DESTDIR.."|"..CAP2
  else
    _, _, DESTFILE=string.find(CAP1,"([^\\\\//]+)$"); 
    REPLACETO=DESTDIR..DESTFILE
  end; 
```

**Comment by daddel80** [comment]
Hi Andry81,

The problem is still with the CAP2, which will only be read if there is a pipe in the line. This will trigger copying CAP1 as DESTDIR, but in line 4 there is no pipe, so DESTDIR will not be set properly.

I think a different approach might be more understandable. Instead of working with CAPs here, it would be easier to handle the string inside the code.

Try this ...
Find what:
`^.*$`

Replace with:
```
init({DESTDIR="", REPLACETO="", DEBUG=true});

if MATCH ~= nil and string.sub(MATCH, 1, 3) == "#> " then
  if string.find(string.sub(MATCH, 4), "|") then
    DESTDIR = string.match(string.sub(MATCH, 4), "^(.+)|")
  else
    DESTDIR = string.match(string.sub(MATCH, 4), "^(.*\\)")
  end;
elseif string.sub(MATCH, 1, 1) == "#" then
  REPLACETO = nil;
elseif string.sub(MATCH, 1, 1) ~= "#" and DESTDIR ~= nil and string.len(DESTDIR) > 0 then
  if string.find(MATCH, "|") then
    REPLACETO = DESTDIR .. "|" .. string.match(MATCH, "|(.+)")
  else
    REPLACETO = DESTDIR .. string.match(MATCH, "[^\\|]+$")
  end;
else
  REPLACETO = nil; 
end;

cond(string.sub(MATCH, 1, 1) ~= "#" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO);
```

Let me know if it comes close to your expectations.

**Comment by andry81** [comment]
> The problem is still with the CAP2, which will only be read if there is a pipe in the line. This will trigger copying CAP1 as DESTDIR, but in line 4 there is no pipe, so DESTDIR will not be set properly.

Why? No. I don't see the problem in the code:

```lua
if CAP1 ~= nil and string.sub(CAP1,1,3) == "#> " then
  if CAP2 ~= nil and string.len(CAP2) > 0 then
    DESTDIR=string.sub(CAP1,4,-1)
  else
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^.+(?:\\\\|/)")
  end; 
```

If `CAP1` exists and `CAP2` exists, then `CAP1` is the required directory to copy.
If `CAP1` exists and `CAP2` not exists, then there is no the pipe sign and we just match the string until the end backslash or slash.

So there is no problem with `DESTDIR` assignment.

---

```lua
    DESTDIR = string.match(string.sub(MATCH, 4), "^(.+)|");
    DESTDIR = string.match(string.sub(MATCH, 4), "^(.*\\)");
    REPLACETO = DESTDIR .. "|" .. string.match(MATCH, "|(.+)");
```

I don't see why this works in first place. Most the regexp expressions are not correct.
You have to escape string twice:
1. For LUA string
2. For the inner LUA regexp string escape

So the corrected variant must be:

```lua
    DESTDIR = string.match(string.sub(MATCH, 4), "^(.+)\\|");
    DESTDIR = string.match(string.sub(MATCH, 4), "^(.*\\\\)");
    REPLACETO = DESTDIR .. "|" .. string.match(MATCH, "\\|(.+)");
```

I've already hit that before, the LUA regexp parser works very strangely.

**Comment by andry81** [comment]
I've located the issue.

The LUA does not understand the regexp expression:

```lua
"(?:\\\\|/)"
```

But this works:

```lua
"[\\/]"
```

```lua
init({DESTDIR="",DESTFILE="",REPLACETO=""}); 

if CAP1 ~= nil and string.sub(CAP1,1,3) == "#> " then
  if CAP2 ~= nil and string.len(CAP2) > 0 then
    DESTDIR=string.sub(CAP1,4,-1)
  else
    DESTDIR=string.match(string.sub(CAP1,4,-1),"^.+[\\/]")
  end; 
elseif CAP1 ~= nil and string.sub(CAP1,1,1) ~= "#" and DESTDIR ~= nil and string.len(DESTDIR) > 0 then
  if CAP2 ~= nil then
    REPLACETO=DESTDIR.."|"..CAP2
  else
    _, _, DESTFILE=string.find(CAP1,"([^\\\\//]+)$"); 
    REPLACETO=DESTDIR..DESTFILE
  end; 
else
  REPLACETO=nil 
end; 

cond(CAP1 ~= nil and string.len(CAP1) > 0 and string.sub(CAP1,1,1) ~= "#" and REPLACETO ~= nil and string.len(REPLACETO) > 0, REPLACETO)
```

**Comment by daddel80** [comment]
>> The problem is still with the CAP2, which will only be read if there is a pipe in the line. This will trigger copying CAP1 as DESTDIR, but in line 4 there is no pipe, so DESTDIR will not be set properly.

>Why? No. I don't see the problem in the code:


Yes, but I see your find regex here has a problem! Even your updated code is based on:
^([^\r\n\|]+)(?:\|([^\r\n\|]+)(?:\|([^\r\n\|]+)(?:\|([^\r\n\|]+))?)?)?

Maybe this visualizes it better in a table. For line 2, you will have the DESTDIR set because CAP2 exists. In Line 3 regex find is not splitting the directory correctly from the file because of a missing pipe. And as no CAP2 exists, DESTDIR will not be refreshed with c:\test2. So, you will get c:\test1\ instead of c:\test2\ in line 5, which is something you want to avoid as I understand.

| Source                          | CAP1                    | CAP2          | DESTDIR       |
|---------------------------------|-------------------------|---------------|---------------|
| # dest: "d:\blabla"             |                         |               |               |
| #> c:\test1\|test1.txt.lnk      | #> c:\test1\            | test1.txt.lnk | c:\test1\     |
| D:\test test\test1.txt          | D:\test test\test1.txt  |               | c:\test1\     |
| #> c:\test2\test2.txt.lnk       | #> c:\test2\test2.txt.lnk|              | c:\test1\     |
| D:\test test\|test2.txt         | D:\test test\           | test2.txt     | c:\test1\     |

To avoid confusion, how do you want to approach the problem as I have provided an alternative solution?

**Comment by andry81** [comment]
It works now as expected. Mine table is:

Source | CAP1 | CAP2 | DESTDIR
-- | -- | -- | --
\# dest: "d:\blabla" |   |   |  
\#> c:\test1\|test1.txt.lnk | #> c:\test1\ | test1.txt.lnk | c:\test1\
D:\test test\test1.txt | D:\test test\test1.txt |   | c:\test1\
\#> c:\test2\test2.txt.lnk | #> c:\test2\test2.txt.lnk |   | c:\test2\
D:\test test\|test2.txt | D:\test test\ | test2.txt | c:\test2\

The reason is that the `DESTDIR=string.match(string.sub(CAP1,4,-1),"^.+(?:\\\\|/)")` assignment just does skip on invalid regex expression somehow. Even `nil` is not assigned.

**Comment by daddel80** [comment]
Ok, I see that I didn't use your last code for testing. It's great that it works now!

**Comment by andry81** [comment]
Thx for help!
