### ISSUE TITLE
Regex Replace All and Selection

### ISSUE THREAD

**Issue by andry81** [daddel80/notepadpp-multireplace#50]
The same as here https://github.com/daddel80/notepadpp-multireplace/issues/37

But with enabled Regular Expressions.

**Comment by daddel80** [comment]
Hi andry81,

Thank you for pointing out this error. I took a quick look and believe I’ve identified the usual suspect. However, I still need to run a few more tests to ensure there are no unexpected side effects with this fix.

**Comment by daddel80** [comment]
Hi andry81,

pls check the following [Build #465](https://github.com/daddel80/notepadpp-multireplace/actions/runs/10360347775). This should fix the issue.
