### ISSUE TITLE
Suggestion: Comment entry in replacement list

### ISSUE THREAD

**Issue by Clicketyclick** [daddel80/notepadpp-multireplace#56]
Extending expressions with a comment field. This will be a help to explain why/how the expression is INTENDED.

```diff
- Selected,Find,Replace,WholeWord,MatchCase,UseVariables,Regex,Extended
+ Selected,Find,Replace,WholeWord,MatchCase,UseVariables,Regex,Extended,Comment
```

**Comment by daddel80** [comment]
Thank you for pointing that out. The feature was already on my list. I’ll see if I can include it in the next release.

**Comment by daddel80** [comment]
You can test a pre-release with the comment column by downloading it from [here](https://github.com/daddel80/notepadpp-multireplace/actions/runs/11540507165). The Statistics button has been removed, as column handling is now different. If you do try it out, let me know if it’s intuitive to enable.
Previous list formats are still compatible with the old version.

P.S. Thanks for the Danish translation! :-)

**Comment by Clicketyclick** [comment]
Works just nicely! Tested with ",", ";" and tab "\t" in comment.

There is a "lot" of space left of the table after removing the redundant statistics button
![billede](https://github.com/user-attachments/assets/f08cf79b-d2d0-4d66-82dc-4d40e2692e40)

**Comment by daddel80** [comment]
> There is a "lot" of space left of the table after removing the redundant statistics button

Agree, i will going to adapt this. Thanks for your feedback!

**Comment by daddel80** [comment]
Hi @Clicketyclick,

Thanks for flagging this! The Comments column is hidden by default - you can always toggle it via right-click on the list header. But I agree that's not intuitive when your list already has comments in it.

I've just pushed an update: the Comments column now automatically becomes visible whenever a list containing comments is loaded. Can you grab the latest [build ](https://github.com/daddel80/notepadpp-multireplace/releases/tag/5.0.0.35)and let me know if that fixes it for you?
