### ISSUE TITLE
Suggestion: Reverse Search / Replace

### ISSUE THREAD

**Issue by geeeethub** [daddel80/notepadpp-multireplace#57]
This is a fantastic tool, thank you for making this available.

A quick suggestion would be to add a "Reverse Search / Replace" button or similar. It would take everything the initial search and replace did, but reverse it back to normal. This would make the tool a powerful data anonymizer / de-anonymizer for LLM use.

**Comment by daddel80** [comment]
The version 4.2.0.22 with **lkp functionality**, ideal for anonymization and data scrambling, is now live. It can be [downloaded here](https://github.com/daddel80/notepadpp-multireplace/releases/tag/4.2.0.22) manually until the next Notepad++ release. Feel free to give it a try for first anonymization testings!
