### ISSUE TITLE
Potential Memory Issue

### ISSUE THREAD

**Issue by daddel80** [daddel80/notepadpp-multireplace#60]
Hi @vinsworldcom,

I would truly appreciate your help as my knowledge in this area is quite limited. I’m encountering unexplained crashes in the plugin whenever I create a new vector in the .h file. I suspect this might be a memory issue, but I haven’t been able to pinpoint the root cause.

Perhaps you have an idea of how to approach this problem. In the branch feature/undo, there’s a test scenario with a simulated crash. The crash occurs at line 2230 in the initializeCtrlMap() function and then at line 260 during a simple assignment of a valid value.

Thank you if you can find the time to look into this! I’d truly appreciate it, as I’m currently stuck.

Best regards,
Thomas

**Comment by vinsworldcom** [comment]
@daddel80 unfortunately so is mine.  I am not a C++ programmer, I can just follow instructions in the plugin template and Scintilla documents.  I don't really have a good (or any) understanding of C++ strings, vectors or other data structures, sorry.

**Comment by daddel80** [comment]
@vinsworldcom, thanks for your reply. I’m still investigating. I think I might have crossed some kind of limit somewhere. Maybe there’s something that can be adjusted in the C++ settings—I’ll look into it. Thanks for taking the time to respond!
