### ISSUE TITLE
GUI: Text cutoff at 'Extended'

### ISSUE THREAD

**Issue by daddel80** [daddel80/notepadpp-multireplace#62]
Hi @Davexx,

I’ve opened a new issue on [this link](https://github.com/daddel80/notepadpp-multireplace/issues/61#issuecomment-2513585351) to keep the topics separate.

Thanks for the detailed explanation about the GUI. Windows internally calculates scaling differently than what users see on their screens. For example, 96 DPI internally represents 100% scaling in the settings, while 144 DPI corresponds to 150% scaling in the display settings. The values shown in the display settings are only estimates and are not entirely precise.

Regarding the incorrectly mentioned resolution of your secondary monitor, it could be an issue in the code of the plugin, but for on my system, it is showing the correct result. I’ll take another look at it later. However, please note that the plugin primarily focuses on DPI, not resolution. Resolution does not factor into the plugin’s calculations. The goal is to ensure the font size matches that of Notepad++. It can best be compared with the text in the standard Notepad++ Find window. I hope the Font Size is the same on your PC compared between Plugin and N++ Find Window..

### I noticed that the 'Extended' phrase in the GUI is still not fully displayed. I’ve resized it again in [this linked version](https://github.com/daddel80/notepadpp-multireplace/actions/runs/12144973709). Please install it and send me an updated screenshot.

Thank you—I really appreciate your support. It’s been incredibly helpful. I will also add the Double Click feature into the manual.

P.S. I made some progress today and implemented your idea (if I understood it correctly) in this linked version. Now, if you hover your mouse over truncated text in the Find, Replace, or Comments fields, the full text will be displayed as a tooltip. Let me know if this matches what you had in mind. I’ve also added a new configuration parameter for this feature, named `HoverText`.

**Comment by Davexx** [comment]
Thomas,
You nailed it this time.  Great work on fitting the extended.  
Also the Mouseover looks great and very helpful when the text does not fit.  Handy to quickly verify one's code.  Superb job:
![Mouseover and Extended fix 2024-12-03](https://github.com/user-attachments/assets/23a69844-7dba-4c6e-894c-01bbdd6a5f6e)

This is at `Scale Factor 1.0`  I also tried it at `ScaleFactor 1.5` and it was good too.

I have been inspired to learn more about LUA variables and RegEx as well.  It is so powerful, but yet it is difficult for someone like me, who is not so code adept, to learn it.  Can you recommend any good learning resources you may know of?

**Comment by daddel80** [comment]
Hi Davexx,

Thanks for sending the screenshot. I’m glad to hear that the text hovering feature is helpful. There was a limitation when implementing it with the Windows API, but I managed to find a clever workaround.

Unfortunately, I don’t have a really good tutorial to recommend. However, one thing you should definitely look into is capture groups in regex, as they are incredibly powerful.

If you have any further recommendations feel free to contact me.

**Comment by Davexx** [comment]
Thomas, it was a pleasure collaborating with you.
Thanks again for your incredibly powerful augmentation to Notepad++. I hope MultiReplace continues to grow in popularity!
Davexx
