### ISSUE TITLE
panel redrawn

### ISSUE THREAD

**Issue by Andr1313** [daddel80/notepadpp-multireplace#66]
Hello!
v.4.2.0.22
When the plugin is called for the first time, this panel is redrawn.
![Clip1](https://github.com/user-attachments/assets/b69eeef6-ef14-44e4-8fb9-a1dc4d500c84)

**Comment by daddel80** [comment]
Hi Andr1313,

thank you for pointing that out. I'm currently trying to reproduce the issue. However, I'm having trouble making the ASCII table visible in Notepad++. What plugin is this, or how did you display it? To better understand the issue, do you mean by "redrawn" a brief flickering of the list?

**Comment by Andr1313** [comment]
Hi,
Edit - Character Panel
Edit - Clipboard History
This panel is also used by many plugins (in my case - "Snippets")

**Comment by Andr1313** [comment]
The panel is completely redrawn once (when accessing the plugin for the first time).
Before ----------------------------------------------------------------- After
![Clip3](https://github.com/user-attachments/assets/ace98753-f767-46bf-ab19-87364af92d2b)

**Comment by daddel80** [comment]
Thanks, I’ve never used these before, but I’m still trying to replicate the issue. So far, I haven’t encountered any errors. 

To make it easier to identify the problem, we need to align our versions. Are you using the latest Notepad++ version 8.7.4? [Please use this version which is closest to the one I provided you last time.](https://github.com/daddel80/notepadpp-multireplace/actions/runs/12517582388)

This my test. I did a fresh start of N++, filled the Clibboard History and started the Plugin as described. Attached the animation of my steps:
![MultiReplace_Clipboard](https://github.com/user-attachments/assets/b32bfdcc-d3ed-4297-babf-109f79e3fe59)

**Comment by Andr1313** [comment]
Strange...

Notepad++ v8.7.4   (64-bit)
Build time : Dec  4 2024 - 23:50:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
Placeholders : OFF
DirectWrite : OFF
Multi-instance Mode : monoInst
File Status Auto-Detection : cdEnabledNew (for current file/tab only)
Dark Mode : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1251
Plugins : 
    ComparePlus (1.2)
    HTMLTag (1.5.1.2)
    mimeTools (3.1)
    MultiReplace (4.2.0.22)
    NppConverter (4.6)
    NppExport (0.4)
    NppSnippets (1.7.1)

**Comment by daddel80** [comment]
Did you test it again with the version I linked in my previous message? I just want to make sure there are no code changes that might cause different behavior on both sides.

**Comment by Andr1313** [comment]
Release or Debug?

**Comment by Andr1313** [comment]
MultiReplace-Release-x64 - the same thing...
Rolled back to 4.1.1.2 - the same thing...
This is evident every time after a new launch of Notepad++, when the plugin is accessed for the first time.
Although it's not critical...

Sorry, I barely know English - I use an online translator.

**Comment by daddel80** [comment]
Doesn't matter. Use the release version. Besides, I was just searching the N++ source code for the phrase "The panel is completely redrawn," but it doesn't exist. However, I would assume it should be in the source code as it’s part of the N++ function set.

**Comment by daddel80** [comment]
Remote debugging is not that easy. However, I’m also curious to track this down. I’d like to send you a test plugin to roughly identify the function where it might be happening. I plan to structure it so that the steps are separated by different message boxes you’ll need to confirm. I’m particularly interested in knowing at which point the clipboard gets redrawn. Thanks for your patience!

**Comment by Andr1313** [comment]
By the way.
When switching from v4.1.1.2 to v4.2.0.22, the first entry in the Multi Replace List.ini was distorted
It was:
Selected,Find,Replace,WholeWord,MatchCase,UseVariables,Regex,Extended,Comments
0,"—","–",0,1,0,0,0,""
0,"<a .*?</a>","set('<a l:href=""#n_'..CNT..'"" type=""note"">['..CNT..']</a>')",0,1,1,0,1,""
0,"<section id.*?</p>","set('<section id=""n_'..CNT..'""><title><p>'..CNT..'</p>')",0,1,1,0,1,""
Become:
0,"вЂ”","вЂ“",0,1,0,0,0,""
0,"<a .*?</a>","set('<a l:href=""#n_'..CNT..'"" type=""note"">['..CNT..']</a>')",0,1,1,0,1,""
0,"<section id.*?</p>","set('<section id=""n_'..CNT..'""><title><p>'..CNT..'</p>')",0,1,1,0,1,""

**Comment by daddel80** [comment]
Let's take a deeper dive. In this Plugin version, there are 15 message boxes, one for each initialization step of the plugin. Please confirm each one and observe the "Clipboard History Panel." Let me know which message box appeared right before you see the panel showing the 'redrawn' message. [Here you can download the Test Plugin.](https://github.com/daddel80/notepadpp-multireplace/actions/runs/12528625121)

**Comment by Andr1313** [comment]
Window size initialized

...and maybe Setting loaded

**Comment by daddel80** [comment]
Is it unstable at which step the error occurs? Have you tested it more than once to confirm if it happens consistently after the same message box?

**Comment by Andr1313** [comment]
Yes.
This happens if the panel is not empty.
For clarity, try changing the background color.

**Comment by daddel80** [comment]
is it then showing the 'redrawn' message after "Window size initialized" and (?) "Setting loaded". Can you please confirm .This is odd. But i will investigate

**Comment by Andr1313** [comment]
The 'redrawn' message does not appear

**Comment by daddel80** [comment]
> The 'redrawn' message does not appear

What did you do? Restarted your Windows? 

Anyway, let me provide you with the latest Beta version. This version includes a Multiline Editor when you double-click on a list entry, and I’ve also performed some memory cleanups in the code. Let’s see if the 'redrawn' message disappears with this update. I’ll also take a closer look at the list entries that changed to odd values you told me. [You can download the latest Beta here. ](https://github.com/daddel80/notepadpp-multireplace/actions/runs/12529519610)

**Comment by Andr1313** [comment]
OK! Thanks

**Comment by Andr1313** [comment]
The distortion in Multi Replace List.ini was only present during the transition from v4.1.1.2 to v4.2.0.22
When switching from v4.2.0.22 to v4.3.0.23, everything is fine.

The panel is still being redrawn once. But that's not important.
The plugin works great.
Thank you very much!

**Comment by daddel80** [comment]
> The panel is completely redrawn

The 'redrawn' text seems to be just a visual demonstration added by the user to highlight the issue occurring in the panel. Previously, I misunderstood and thought the 'redrawn' text indicated a cleanup, but this seems to be incorrect. This refresh actually appears to be part of Notepad++ and cannot be influenced by the plugin itself.

Why is this happening? You mentioned that it occurs right after 'Window size initialized.' Since the plugin is a child process of Notepad++, it recognizes the creation of each plugin and is also responsible for managing all elements in the plugin window. This behavior could potentially influence the refresh of the other panel.
